#include "../headers/automata.h"

int create_automata(automata_T * automata){
    automata->cells = (char * ) malloc(automata->size_x * automata->size_y); 
    if(automata->cells == NULL) return -1;
    return 0;
}


/*  Karnaugh map of the cell logic
    L = Life mask generated by the life rule, D = death mask,
    C = cells array

        LD
        00  01  11  10
C = 0 |  0   0   X   1
C = 1 |  1   0   X   1

= C & !(L | D) | L
*/


void iterate_automata(automata_T * automata){
    char * life_mask = (char *) malloc(automata->size_x * automata->size_x);
    char * death_mask = (char *) malloc(automata->size_x * automata->size_x);
    for(int y = 0; y < automata->size_y; y++){
        for(int x = 0; x < automata->size_x; x++){
            int idx = y * automata->size_x + x;
            life_mask[idx] = automata->rule_life(automata, x, y);
            death_mask[idx] = automata->rule_death(automata, x, y);
        }
    }
    for(int y = 0; y < automata->size_y; y++){
        for(int x = 0; x < automata->size_x; x++){
            int idx = y * automata->size_x + x;
            automata->cells[idx] = (automata->cells[idx] & !(life_mask[idx] | death_mask[idx])) | life_mask[idx]; 
        }
    }

}

void destroy_automata(automata_T * automata){
    free(automata->cells);
}

int flow_bounds(int x, int min, int max){
    int size = max - min;
    while(x > max) x -= size;
    while(x < min) x += size;
    return x;
}

int count_cell_neighbors_wrap(automata_T * automata, int x, int y){
    int count = 0;
    int w = automata->size_x;
    int h = automata->size_y;

    for (int dy = -1; dy <= 1; dy++) {
        for (int dx = -1; dx <= 1; dx++) {
            if (dx == 0 && dy == 0) continue; // skip self
            int nx = flow_bounds(x + dx, 0, w - 1);
            int ny = flow_bounds(y + dy, 0, h - 1);
            if (nx < 0 || nx >= w || ny < 0 || ny >= h) continue;
            count += automata->cells[ny * w + nx];
        }
    }
    return count;
}

